services:
  - type: web
    plan: free
    name: Sharingan-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Avuf/File-sharing-Bot      
    branch: main
    envVars:
      - key: API_HASH
        sync: false
      - key: APP_ID
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL 
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: ADMINS
        sync: false
    autoDeploy: false
